// (C) 2025-2026 MWBM Partners Ltd
//
// MeedyaManager — mm-ffi build script
//
// Generates the C header (`include/mm_ffi.h`) from all `#[no_mangle] extern "C"`
// functions in `src/capi.rs` using cbindgen.  This header is consumed by
// the Windows WinUI 3 C# project via P/Invoke.
//
// UniFFI scaffolding is handled by the proc-macro approach (`setup_scaffolding!`)
// so no separate build-time UDL processing is required here.

use std::env;
use std::path::PathBuf;

fn main() {
    // -----------------------------------------------------------------------
    // cbindgen — generate C header from #[no_mangle] extern "C" functions
    // -----------------------------------------------------------------------

    // Locate the crate root (directory containing this build.rs)
    let crate_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR is not set — must run inside Cargo");

    // Output: <workspace-root>/include/mm_ffi.h
    // The Windows C# project references this via a relative path.
    let workspace_root = PathBuf::from(&crate_dir)
        .parent() // crates/
        .and_then(|p| p.parent()) // workspace root
        .expect("Could not resolve workspace root from CARGO_MANIFEST_DIR")
        .to_path_buf();

    let include_dir = workspace_root.join("include");

    // Create the include/ directory if needed
    std::fs::create_dir_all(&include_dir).expect("Failed to create workspace include/ directory");

    let header_path = include_dir.join("mm_ffi.h");

    // Load cbindgen.toml config if present, otherwise use defaults
    let config = cbindgen::Config::from_file(PathBuf::from(&crate_dir).join("cbindgen.toml"))
        .unwrap_or_default();

    // Run cbindgen and write the C header
    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .with_language(cbindgen::Language::C)
        .with_include_version(true)
        .with_header(concat!(
            "/* (C) 2025-2026 MWBM Partners Ltd\n",
            " * MeedyaManager C API — generated by cbindgen, do not edit.\n",
            " * Used by the Windows WinUI 3 C# project via P/Invoke.\n",
            " */"
        ))
        .generate()
        .unwrap_or_else(|e| panic!("cbindgen failed: {e}"))
        .write_to_file(&header_path);

    // Re-run this script whenever any source file changes
    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=cbindgen.toml");
}
