// (C) 2025-2026 MWBM Partners Ltd
//
// MeedyaManager — mm-ffi build script
//
// Generates the C header (`include/mm_ffi.h`) from all `#[no_mangle] extern "C"`
// functions in `src/capi.rs` using cbindgen.  This header is consumed by
// the Windows WinUI 3 C# project via P/Invoke.
//
// UniFFI scaffolding is handled by the proc-macro approach (`setup_scaffolding!`)
// so no separate build-time UDL processing is required here.

use std::env;
use std::path::PathBuf;

fn main() {
    // -----------------------------------------------------------------------
    // cbindgen — generate C header from #[no_mangle] extern "C" functions
    // -----------------------------------------------------------------------

    // Locate the crate root (directory containing this build.rs)
    let crate_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR is not set — must run inside Cargo");

    // Output: <workspace-root>/include/mm_ffi.h
    // The Windows C# project references this via a relative path.
    let workspace_root = PathBuf::from(&crate_dir)
        .parent() // crates/
        .and_then(|p| p.parent()) // workspace root
        .expect("Could not resolve workspace root from CARGO_MANIFEST_DIR")
        .to_path_buf();

    let include_dir = workspace_root.join("include");

    // Create the include/ directory if needed
    std::fs::create_dir_all(&include_dir).expect("Failed to create workspace include/ directory");

    let header_path = include_dir.join("mm_ffi.h");

    // Load cbindgen.toml. Unlike the previous `.unwrap_or_default()`, a parse
    // failure here is fatal: issue #64 was exactly this kind of silent
    // fallback — a config with three invalid/unrecognised keys (see the
    // comments in cbindgen.toml) meant cbindgen quietly generated from
    // `Config::default()`, and nobody noticed the header was empty until a
    // human went looking.
    let config_path = PathBuf::from(&crate_dir).join("cbindgen.toml");
    let config = cbindgen::Config::from_file(&config_path).unwrap_or_else(|e| {
        panic!(
            "failed to parse {}: {e}\n\
             (a bad cbindgen.toml must fail the build loudly, not fall back to \
             defaults — see issue #64)",
            config_path.display()
        )
    });

    // Run cbindgen and write the C header
    let bindings = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .with_language(cbindgen::Language::C)
        .with_include_version(true)
        .with_header(concat!(
            "/* (C) 2025-2026 MWBM Partners Ltd\n",
            " * MeedyaManager C API — generated by cbindgen, do not edit.\n",
            " * Used by the Windows WinUI 3 C# project via P/Invoke.\n",
            " */"
        ))
        .generate()
        .unwrap_or_else(|e| panic!("cbindgen failed: {e}"));

    bindings.write_to_file(&header_path);

    // -----------------------------------------------------------------------
    // Guard against a repeat of issue #64: a header cbindgen "successfully"
    // generated but which declares zero (or suspiciously few) `mm_ffi_*`
    // prototypes is worse than a build failure — it ships silently and every
    // Windows P/Invoke signature goes unverified against it. capi.rs defines
    // 11 `#[unsafe(no_mangle)] pub extern "C" fn mm_ffi_*` functions today, so
    // fail the build outright if the generated header contains fewer than 11
    // `mm_ffi_` occurrences (each prototype's name appears once).
    // -----------------------------------------------------------------------
    const MIN_MM_FFI_PROTOTYPES: usize = 11;
    let header_text =
        std::fs::read_to_string(&header_path).expect("just-written header must be readable");
    let prototype_count = header_text.matches("mm_ffi_").count();
    assert!(
        prototype_count >= MIN_MM_FFI_PROTOTYPES,
        "generated {} declares only {prototype_count} `mm_ffi_` occurrence(s), \
         expected at least {MIN_MM_FFI_PROTOTYPES} — cbindgen likely exported \
         nothing (see issue #64: check cbindgen.toml and that capi.rs functions \
         use an attribute form this cbindgen version recognises)",
        header_path.display()
    );

    // Re-run this script whenever any source file changes
    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=cbindgen.toml");
}
