// (C) 2025-2026 MWBM Partners Ltd
//
// MeedyaManager — Shared HTTP Client Builder (mm-providers)
//
// All metadata provider structs should construct their `reqwest::Client`
// through `build_client()` rather than `reqwest::Client::new()`.
//
// This ensures every outbound HTTP request carries a consistent, accurate
// User-Agent header that identifies MeedyaManager to remote APIs, rather
// than the default `reqwest/<version>` which many APIs log or throttle.
//
// The user-agent string is generated by `mm_core::useragent::build_user_agent()`,
// which produces strings like:
//   MeedyaManager/1.2.0 (macOS; Apple Silicon)
//   MeedyaManager/1.2.0 (Windows; x64)
//   MeedyaManager/1.2.0 (Linux; ARM64)
//
// Public API:
//   build_client() → reqwest::Client    — pre-configured client with our UA

/// Build a `reqwest::Client` pre-configured with the MeedyaManager User-Agent.
///
/// # Panics
/// Panics if the reqwest `ClientBuilder` fails — this only happens if TLS
/// initialisation fails, which is a fatal startup condition.
pub fn build_client() -> reqwest::Client {
    // Resolve the platform-accurate user-agent string from mm-core
    let ua = mm_core::useragent::build_user_agent();

    reqwest::Client::builder()
        // Set the User-Agent header as a default on every request from this client.
        // Individual requests may override it with .header("User-Agent", ...) if
        // a specific provider has its own UA requirement (e.g. MusicBrainz).
        .user_agent(ua)
        // Build and unwrap: ClientBuilder only fails if TLS initialisation fails,
        // which is a fatal condition — crashing here is the correct behaviour.
        .build()
        .expect("reqwest ClientBuilder failed — TLS initialisation error")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn build_client_succeeds() {
        // Smoke test — just verify the builder doesn't panic.
        let _client = build_client();
    }

    #[test]
    fn multiple_clients_can_be_built() {
        // Verify there's no global state that prevents multiple client instances.
        let _a = build_client();
        let _b = build_client();
    }
}
