/* (C) 2025-2026 MWBM Partners Ltd
 * MeedyaManager C API — generated by cbindgen, do not edit.
 * Used by the Windows WinUI 3 C# project via P/Invoke.
 */

/* Generated with cbindgen:0.27.0 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
